### ISSUE TITLE
Symbolic links for knife etc conflict when installing ChefDK and Chef Client

### ISSUE THREAD

**Issue by BackSlasher** [opscode/omnibus-chef#319]
When running Ubuntu 14.04, After installing the following in that order:
* Chef client latest (12.0.3-1)
* ChefDK latest (0.3.5)

And running `knife --version`, I get version 11.  
This is an issue because after installing ChefDK, I was unable to bootstrap Chef 12 clients (because Knife 11 wouldn't copy self-signed certificates like Knife 12 does).

This is because both packages include knife, and each is overwriting `/usr/bin/knife`, meaning the last installed product "wins".
Instead of using [`ln -sf`](https://github.com/opscode/omnibus-chef/blob/master/package-scripts/chefdk/postinst#L39), one could use [Debian alternatives](https://www.debian-administration.org/article/91/Using_the_Debian_alternatives_system), allowing both Knife versions from ChefDK and Chef Client to coexist.
Or one can avoid overwriting the link if it points to a newer version.

**Comment by lamont-granquist** [comment]
This issue goes away with ChefDK 0.4.0 which will ship with Chef 12.   It also can be solved by putting the /opt/chef/bin directory first in the path before /opt/chefdk/bin so that knife resolves to knife 12.

**Comment by BackSlasher** [comment]
@lamont-granquist I think this issue will reoccur the next time there's a functional difference between the latest client and the latest DK. Don't you think the installation script should at least print an error when there's an existing (and valid) symlink?

I'll be happy to help, I just want to get your idea of what's a good solution before I work on it.

**Comment by lamont-granquist** [comment]
Well from our perspective generally the best solution is to just ship a new chefdk.  That normally isn't that hard to do but it got caught up in a yak shave around doing this last 0.3.x ChefDK release with certain windows fixes in it which must be on Chef 11, which is then blocking 0.4.x and shipping with chef-12 by default, which was then interrupted by everyone leaving on vacation and not wanting to ship on the friday before everyone vanished.  So this is mostly all temporary (and largely self-generated) schedule problems that all go away once we press the button on 0.4.0.  

Maybe the installer should warn on overwriting the symlinks, but ideally people are not installing both chef and chefdk on the same machine since chef comes with chefdk.  You're only do that because we have these scheduling problems around chef 12.

So, yeah warnings would be fine.  In order to be compliant with the principles of omnibus, though, doing alternatives would require importing alternatives into the omnibus build and porting it to Solaris and AIX and everything else that we'll wind up supporting going forwards.  We won't accept having debian/ubuntu behave one way and be special because they're better and then have to special case instructions for users on other operating systems.   So alternatives falls under the 'if we had infinite time that'd be cool' kind of yak shave, so I'd be :-1: even if someone did the patches, because I don't want the support burden going forwards every time we pick up a new O/S variant.

**Comment by mmell** [comment]
The [chef client download page](https://www.chef.io/download-chef-client/) should make clear that a workstation needs the ChefDK and probably not the chef-client.

**Comment by fsimmend** [comment]
But how should we manage a CI (Jenkins) server with chef, when the CI server needs chef-dk to run its jobs ?
